---
title: "Figures for BLM-Elevation"
author: "AMS, on behalf of Holbrook et al"
date: "29 July, 2022"
output: 
  pdf_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

# reporting packages
library(yarrr)
library(ggiraphExtra)
library(correlation)
library(grid)
library(gridExtra)
library(scales)
# library(cowplot)
# library(leaps)
#library(afex)
#library(sjPlot)
#library(performance)

# data prep 
source("BLM-elevation_data-prep.R")

# palettes that work for our color-blind friends
source("BLM-elevation_palettes.R")

# plot
source("BLM-elevation_useful-plots.R")

```

# Figures

These Figures are used in the Main Text and/or Supplement to Holbrook et al "The Coalitional Contours of Moral Elevation: Evidence from the U.S. Black Lives Matter Protest and Counter-protest Movements."

```{r fig.cap = "Main Text Figure 1. Elevation by Condition."}
pirateplot(
  formula = elevation ~ condition + study,
  data = bind_rows(
    list(
      `Study 1` =    study1$df %>% select(elevation, condition),
      `Study 2` =    study2$df %>% select(elevation, condition)
    ),
    .id = "study"
  ),
  pal = conditions_palette, 
  theme = 1,
  cex.lab = 1.5
) 
```

```{r fig.cap="Main Text Figure 2"}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "elevation",
                       ylab = "elevation",
                       group = "condition")

```

```{r fig.cap="Main Text Figure 3."}
custom_scatterplot_all(x = "police_funding",
                       xlab = "police funding preference",
                       y = "elevation",
                       ylab= "elevation",
                       group = "condition")

```

```{r fig.cap = "Supplement Figure S1. Just like Main Text Figure 2, except using elevation subscales rather than the full elevation scale"}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "folk_affect",
                       ylab= "folk affect",
                       group = "condition")

```

```{r fig.cap = "Supplement Figure S2. Just like Main Text Figure 2, except using elevation subscale rather than the full elevation scale"}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "somatic",
                       ylab= "somatic",
                       group = "condition")

```

```{r fig.cap = "Supplement Figure S3. Just like Main Text Figure 2, except using elevation subscale rather than the full elevation scale"}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "prosocial_motives",
                       ylab= "prosocial motives",
                       group = "condition")

```

```{r fig.cap="Supplement Figure S4. Like Main Text Figure 2, except using Idealism towards Police instead of Conservatism"}
custom_scatterplot_all(x = "idealism_police",
                       xlab = "idealism towards police",
                       y = "elevation",
                       ylab= "elevation",
                       group = "condition")

```

```{r fig.cap="Supplement Figure S5. Like Main Text Figure 2, except using Idealism towards BLM instead of Conservatism. Note: study 2 data only"}
custom_scatterplot(x="idealism_blm", xlab = "idealism towards BLM", y = "elevation", ylab = "elevation")
```

```{r fig.cap = "Supplement Figure S6. Police Funding by Condition."}
pirateplot(
  formula = police_funding ~ condition + study,
  data = bind_rows(
    list(
      `Study 1` =    study1$df %>% select(police_funding, condition),
      `Study 2` =    study2$df %>% select(police_funding, condition)
    ),
    .id = "study"
  ),
  pal = conditions_palette, 
  theme = 1,
  cex.lab = 1.5
) 
```
