---
title: "Figures for Colin March 12 2022"
author: "AMS"
date: "Mar 12, 2022"
output: 
  pdf_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

# reporting packages
library(yarrr)
library(ggiraphExtra)
library(correlation)
library(grid)
library(gridExtra)
library(scales)
# library(cowplot)
# library(leaps)
#library(afex)
#library(sjPlot)
#library(performance)

# data prep 
source("PAPER1_data-prep.R")

# palettes that work for our color-blind friends
source("PAPER1_palettes.R")

# plot
source("PAPER1_useful-plots.R")



```

# Elevation by condition

```{r fig.cap = "study 1. Currently Main Text Fig 1 top"}
pirateplot(
  formula = elevation ~ condition,
  data = study1$df,
  pal = conditions_palette[c(1,3)], # not sure why this is necessary
  theme = 1,
  gl.y = 0,
  cex.lab = 1.5
) 

```

```{r fig.cap = "study 2. Currently Main Text Fig 1 bottom"}
pirateplot(
  formula = elevation ~ condition,
  data = study2$df,
  pal = conditions_palette, 
  theme = 1,
  gl.y = 0,
  cex.lab = 1.5
) 

```

# Police Funding by Condition

```{r fig.cap="Supplement Fig S6 top panel for study 1"}
pirateplot(
  formula = police_funding ~ condition,
  data = study1$df,
  pal = conditions_palette[c(1,3)], # not sure why this is necessary
  theme = 1,
  gl.y = 0,
  cex.lab = 1.5
) 

```

```{r fig.cap="Supplement Fig S6 bottom panel for study 2"}
pirateplot(
  formula = police_funding ~ condition,
  data = study2$df,
  pal = conditions_palette,
  theme = 1,
  gl.y = 0,
  cex.lab = 1.5
) 

```

# Elevation by Conservativism

```{r fig.cap="Main Text currently has this as Fig 2, but arguably could be promoted to Fig 1"}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "elevation",
                       ylab = "elevation",
                       group = "condition")

```

# Subscales

```{r}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "prosocial_motives",
                       ylab= "prosocial motives",
                       group = "condition")

```

```{r}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "somatic",
                       ylab= "somatic",
                       group = "condition")

```

```{r}
custom_scatterplot_all(x = "conservativism_overall",
                       xlab = "conservatism",
                       y = "folk_affect",
                       ylab= "folk affect",
                       group = "condition")

```

# Funding Pref

```{r}
custom_scatterplot_all(x = "police_funding",
                       xlab = "police funding preference",
                       y = "elevation",
                       ylab= "elevation",
                       group = "condition")

```

# Idealisms

```{r}
custom_scatterplot_all(x = "idealism_police",
                       xlab = "idealism towards police",
                       y = "elevation",
                       ylab= "elevation",
                       group = "condition")

```

```{r fig.cap="study 2 data only"}
custom_scatterplot(x="idealism_blm", xlab = "idealism towards BLM", y = "elevation", ylab = "elevation")
```
